package model

type Fragment struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	FullTitle   string `json:"fullTitle"`
	Description string `json:"description"`
	CollectedAt string `json:"collectedAt,omitzero"`
	// Position data (generated by seeded RNG based on date)
	PositionX float64 `json:"positionX"` // 5-65%
	PositionY float64 `json:"positionY"` // 8-83%
	Angle     float64 `json:"angle"`     // -15 to 15 degrees
}

type Creation struct {
	ID        int64  `json:"id"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type PaginatedResult struct {
	Items    any  `json:"items"`
	Total    int  `json:"total"`
	Page     int  `json:"page"`
	PageSize int  `json:"pageSize"`
	HasMore  bool `json:"hasMore"`
}

func PaginatedSlice[T any](items []T, total, page, pageSize int) *PaginatedResult {
	start := (page - 1) * pageSize
	if start >= total {
		return &PaginatedResult{Items: []T{}, Total: total, Page: page, PageSize: pageSize, HasMore: false}
	}
	return &PaginatedResult{Items: items, Total: total, Page: page, PageSize: pageSize, HasMore: start+len(items) < total}
}
