package main

import (
	"context"
	"fmt"
	"math/rand/v2"
	"os"
	"path/filepath"
	"slices"
	"time"
)

type Fragment struct {
	ID          int64  `json:"id"`
	Title       string `json:"title"`
	FullTitle   string `json:"fullTitle"`
	Description string `json:"description"`
	CollectedAt string `json:"collectedAt,omitzero"`
	// Position data (generated by seeded RNG based on date)
	PositionX float64 `json:"positionX"` // 5-65%
	PositionY float64 `json:"positionY"` // 8-83%
	Angle     float64 `json:"angle"`     // -15 to 15 degrees
}

type Creation struct {
	ID        int64  `json:"id"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type PaginatedResult struct {
	Items    any  `json:"items"`
	Total    int  `json:"total"`
	Page     int  `json:"page"`
	PageSize int  `json:"pageSize"`
	HasMore  bool `json:"hasMore"`
}

type App struct {
	ctx context.Context
}

func paginatedSlice[T any](items []T, total, page, pageSize int) *PaginatedResult {
	start := (page - 1) * pageSize
	if start >= total {
		return &PaginatedResult{Items: []T{}, Total: total, Page: page, PageSize: pageSize, HasMore: false}
	}
	return &PaginatedResult{Items: items, Total: total, Page: page, PageSize: pageSize, HasMore: start+len(items) < total}
}

var fragmentPool = []Fragment{
	{
		Title:       "希█",
		FullTitle:   "希望",
		Description: "像眼睛，望着他，望了很久。",
	},
	{
		Title:       "█支装",
		FullTitle:   "廿支装",
		Description: "两根竖线，下边相连。父亲说是二十的意思。",
	},
	{
		Title:       "█天",
		FullTitle:   "春天",
		Description: "新学期发书了，闻着油墨味儿阅读，即使不认识的字都富有美感",
	},
	{
		Title:       "█水",
		FullTitle:   "山水",
		Description: "弯弯曲曲的，像山，又像水。他蹲在那面墙前看了很久。",
	},
	{
		Title:       "远█",
		FullTitle:   "远方",
		Description: "不知道那远方究竟有多远，但心里会有一种说不清的跳动。",
	},
	{
		Title:       "█子",
		FullTitle:   "竹子",
		Description: "竹叶上挂着露珠，晶莹的，像字。",
	},
	{
		Title:       "█字",
		FullTitle:   "识字",
		Description: "捧着课本，一个字一个字地认，觉得认识一个字就像交到一个朋友。",
	},
	{
		Title:       "█光",
		FullTitle:   "目光",
		Description: "老师的目光落在黑板上，他跟着那个目光，看到了一个他从没去过的世界。",
	},
	{
		Title:       "电█院",
		FullTitle:   "电影院",
		Description: "只在露天电影里见过。白色的幕布撑在星空下，人影晃动，声音很远。",
	},
	{
		Title:       "█歌",
		FullTitle:   "山歌",
		Description: "村里有人唱，他听不懂词儿，只觉得那声音顺着风，传得很远。",
	},
	{
		Title:       "█念",
		FullTitle:   "信念",
		Description: "不知道这两个字是什么意思，觉得听起来有力量。",
	},
}

func (a *App) startup(ctx context.Context) {
	a.ctx = ctx

	homeDir, err := os.UserHomeDir()
	if err != nil {
		fmt.Printf("Failed to get home dir: %v\n", err)
		return
	}

	dataDir := filepath.Join(homeDir, ".still_wtzn")

	if err := os.MkdirAll(dataDir, 0755); err != nil {
		fmt.Printf("Failed to create data dir: %v\n", err)
		return
	}

	if err := initDB(dataDir); err != nil {
		fmt.Printf("Failed to init db: %v\n", err)
		return
	}
}

func (a *App) shutdown(ctx context.Context) {
	closeDB()
}

func (a *App) GetDataDir() string {
	homeDir, _ := os.UserHomeDir()
	return filepath.Join(homeDir, ".still_wtzn")
}

func (a *App) GetFragmentPool() []Fragment {
	return fragmentPool
}

func (a *App) GetFragments(page, pageSize int) (*PaginatedResult, error) {
	rows, err := db.Query("SELECT full_title FROM collected")
	if err != nil {
		return nil, fmt.Errorf("query collected full_title failed: %w", err)
	}
	defer rows.Close()

	collectedMap := make(map[string]bool)
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			continue
		}
		collectedMap[t] = true
	}

	seed := time.Now().UnixNano()
	rng := newSeededRandom(seed)

	pool := slices.Clone(fragmentPool)

	selected := []Fragment{}

	for len(selected) < 1 && len(pool) > 0 {
		idx := int(rng.Float64() * float64(len(pool)))
		frag := pool[idx]
		pool = append(pool[:idx], pool[idx+1:]...)
		if collectedMap[frag.FullTitle] {
			continue
		}
		frag.PositionX = 5 + rng.Float64()*60
		frag.PositionY = 8 + rng.Float64()*75
		frag.Angle = rng.Float64()*30 - 15
		selected = append(selected, frag)
	}

	if len(selected) == 0 {
		println("GetFragments: WARNING - no fragments selected!")
	}
	return paginatedSlice(selected, len(selected), page, pageSize), nil
}

func newSeededRandom(seed int64) *rand.Rand {
	return rand.New(rand.NewPCG(uint64(seed), uint64(seed)))
}

func (a *App) LoadCollected(page, pageSize int) (*PaginatedResult, error) {
	fragments, total, err := dbLoadCollected(page, pageSize)
	if err != nil {
		return nil, err
	}
	return paginatedSlice(fragments, total, page, pageSize), nil
}

func (a *App) SaveFragment(frag Fragment) (int64, error) {
	return dbSaveFragment(frag)
}

func (a *App) LoadCreations(page, pageSize int) (*PaginatedResult, error) {
	creations, total, err := dbLoadCreations(page, pageSize)
	if err != nil {
		return nil, err
	}
	return paginatedSlice(creations, total, page, pageSize), nil
}

func (a *App) SaveCreation(content string) (*Creation, error) {
	id, createdAt, err := dbSaveCreation(content)
	if err != nil {
		return nil, err
	}

	return &Creation{
		ID:        id,
		Content:   content,
		CreatedAt: createdAt,
	}, nil
}

func (a *App) ClearCreations() error {
	return dbClearCreations()
}

func (a *App) ClearCollected() error {
	return dbClearCollected()
}

func (a *App) ResetGame() error {
	if err := dbClearCreations(); err != nil {
		return err
	}
	return dbClearCollected()
}
