package main

import (
	"context"
	"fmt"
	"os"
	"path/filepath"
	"time"
)

type Fragment struct {
	ID          int64  `json:"id"`
	Type        string `json:"type"`
	Title       string `json:"title"`
	FullTitle   string `json:"fullTitle"`
	Description string `json:"description"`
	CollectedAt string `json:"collectedAt"`
	// Position data (generated by seeded RNG based on date)
	PositionX float64 `json:"positionX"` // 5-65%
	PositionY float64 `json:"positionY"` // 8-83%
	Angle     float64 `json:"angle"`     // -15 to 15 degrees
}

type Creation struct {
	ID        int64  `json:"id"`
	Content   string `json:"content"`
	CreatedAt string `json:"createdAt"`
}

type PaginatedResult struct {
	Items    interface{} `json:"items"`
	Total    int         `json:"total"`
	Page     int         `json:"page"`
	PageSize int         `json:"pageSize"`
	HasMore  bool        `json:"hasMore"`
}

type App struct {
	ctx context.Context
}

var fragmentPool = []Fragment{
	{
		Type:        "cigarette-box",
		Title:       "廿支装",
		FullTitle:   "廿支装",
		Description: "那个字，他念不出来，却记住了它的形状。两根竖线，像两个人并肩站着，中间还连着什么。问了父亲，父亲说那是二十的意思。他点点头，二十支烟，装在一个小小的盒子里。这个字，从此住进了心里。",
	},
	{
		Type:        "newspaper",
		Title:       "█望",
		FullTitle:   "希望",
		Description: `路边捡到的，半张纸，字迹模糊得只剩半边。左边那个字残了，看不清是什么。右边的"望"字倒还完整，像一只眼睛，望着他，望了很久。他把纸小心地折好，揣进兜里，带回家反复地看。`,
	},
	{
		Type:        "textbook",
		Title:       "█天",
		FullTitle:   "春天",
		Description: "新学期发书那天，油墨香是新的。他把语文课本从头翻到尾，一天之内，全部看完。有个生字不认识，也没去查，就自己猜了一个意思。后来才知道猜错了。但那个错误的意思，他觉得比正确的还要好，像春天里一场模糊的雨。",
	},
	{
		Type:        "envelope",
		Title:       "█方",
		FullTitle:   "远方",
		Description: `信封已经旧了，寄信人和收信人的名字都褪了色。只剩下"远方"两个字，还有一个模糊的邮戳。他不知道是谁写给谁的信，也不知道那远方究竟有多远。但每次看到这两个字，心里就会有一种说不清的跳动，像有什么东西在等他。`,
	},
	{
		Type:        "wall",
		Title:       "山水",
		FullTitle:   "山水",
		Description: "墙上刷的是石灰水，却有人用炭棒在上面画了些笔画。弯弯曲曲的，像山，又像水。他蹲在那面墙前看了很久，想象那些线条的另一头连着什么。",
	},
	{
		Type:        "bamboo",
		Title:       "竹子",
		FullTitle:   "竹子",
		Description: `暑假住在山里亲戚家，屋后有一片竹林。早起看见竹叶上挂着露珠，晶莹的，像字。他采了一片夹进书里，说是要记住这个"竹"字的样子。`,
	},
}

func NewApp() *App {
	return &App{}
}

func (a *App) startup(ctx context.Context) {
	a.ctx = ctx

	homeDir, err := os.UserHomeDir()
	if err != nil {
		fmt.Printf("Failed to get home dir: %v\n", err)
		return
	}

	dataDir := filepath.Join(homeDir, ".still_wtzn")

	if err := os.MkdirAll(dataDir, 0755); err != nil {
		fmt.Printf("Failed to create data dir: %v\n", err)
		return
	}

	if err := initDB(dataDir); err != nil {
		fmt.Printf("Failed to init db: %v\n", err)
		return
	}
}

func (a *App) shutdown(ctx context.Context) {
	closeDB()
}

func (a *App) GetDataDir() string {
	homeDir, _ := os.UserHomeDir()
	return filepath.Join(homeDir, ".still_wtzn")
}

func (a *App) GetFragmentPool() []Fragment {
	return fragmentPool
}

func (a *App) GetTodayFragments(page, pageSize int) (*PaginatedResult, error) {
	rows, err := db.Query("SELECT type FROM collected")
	if err != nil {
		return nil, fmt.Errorf("query collected types failed: %w", err)
	}
	defer rows.Close()

	collectedMap := make(map[string]bool)
	for rows.Next() {
		var t string
		if err := rows.Scan(&t); err != nil {
			continue
		}
		collectedMap[t] = true
	}

	seed := getDateSeed()
	rng := newSeededRandom(seed)

	pool := make([]Fragment, len(fragmentPool))
	copy(pool, fragmentPool)

	selected := []Fragment{}

	for len(selected) < 1 && len(pool) > 0 {
		idx := int(rng() * float64(len(pool)))
		frag := pool[idx]
		pool = append(pool[:idx], pool[idx+1:]...)
		if collectedMap[frag.Type] {
			continue
		}
		frag.PositionX = 5 + rng()*60
		frag.PositionY = 8 + rng()*75
		frag.Angle = rng()*30 - 15
		selected = append(selected, frag)
	}

	total := len(selected)
	start := (page - 1) * pageSize
	end := start + pageSize

	var debugMsg string
	if start > total {
		debugMsg = fmt.Sprintf("GetToday: collectedMap size=%d, pool=%d, total=%d, start=%d", len(collectedMap), len(pool), total, start)
		println(debugMsg)
		return &PaginatedResult{
			Items:    []Fragment{},
			Total:    total,
			Page:     page,
			PageSize: pageSize,
			HasMore:  false,
		}, nil
	}

	if end > total {
		end = total
	}

	debugMsg = fmt.Sprintf("GetToday: collectedMap size=%d, pool=%d, total=%d, returning=%d", len(collectedMap), len(pool), total, len(selected[start:end]))
	println(debugMsg)
	if len(selected) == 0 {
		println("GetToday: WARNING - no fragments selected!")
	}

	return &PaginatedResult{
		Items:    selected[start:end],
		Total:    total,
		Page:     page,
		PageSize: pageSize,
		HasMore:  end < total,
	}, nil
}

func getDateSeed() int64 {
	d := time.Now()
	return int64(d.Year()*10000 + int(d.Month())*100 + d.Day())
}

func newSeededRandom(seed int64) func() float64 {
	m := int64(0x80000000)
	a := int64(1103515245)
	c := int64(12345)
	state := seed
	return func() float64 {
		state = (a*state + c) % m
		return float64(state) / float64(m)
	}
}

func (a *App) LoadCollected(page, pageSize int) (*PaginatedResult, error) {
	fragments, total, err := dbLoadCollected(page, pageSize)
	if err != nil {
		return nil, err
	}

	totalCount := total
	start := (page - 1) * pageSize
	end := start + pageSize

	if start > totalCount {
		return &PaginatedResult{
			Items:    []Fragment{},
			Total:    totalCount,
			Page:     page,
			PageSize: pageSize,
			HasMore:  false,
		}, nil
	}

	if end > totalCount {
		end = totalCount
	}

	return &PaginatedResult{
		Items:    fragments,
		Total:    totalCount,
		Page:     page,
		PageSize: pageSize,
		HasMore:  end < totalCount,
	}, nil
}

func (a *App) SaveFragment(frag Fragment) error {
	return dbSaveFragment(frag)
}

func (a *App) LoadCreations(page, pageSize int) (*PaginatedResult, error) {
	creations, total, err := dbLoadCreations(page, pageSize)
	if err != nil {
		return nil, err
	}

	totalCount := total
	start := (page - 1) * pageSize
	end := start + pageSize

	if start > totalCount {
		return &PaginatedResult{
			Items:    []Creation{},
			Total:    totalCount,
			Page:     page,
			PageSize: pageSize,
			HasMore:  false,
		}, nil
	}

	if end > totalCount {
		end = totalCount
	}

	return &PaginatedResult{
		Items:    creations,
		Total:    totalCount,
		Page:     page,
		PageSize: pageSize,
		HasMore:  end < totalCount,
	}, nil
}

func (a *App) SaveCreation(content string) (*Creation, error) {
	id, createdAt, err := dbSaveCreation(content)
	if err != nil {
		return nil, err
	}

	return &Creation{
		ID:        id,
		Content:   content,
		CreatedAt: createdAt,
	}, nil
}

func (a *App) ClearCreations() error {
	return dbClearCreations()
}

func (a *App) ClearCollected() error {
	return dbClearCollected()
}

func (a *App) ResetGame() error {
	if err := dbClearCreations(); err != nil {
		return err
	}
	return dbClearCollected()
}
