// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {model} from '../models';

export function GenFragment():Promise<model.Fragment>;

export function LoadCollected():Promise<Array<model.Fragment>>;

export function LoadCreations(arg1:number,arg2:number):Promise<model.PaginatedResult>;

export function ResetGame():Promise<void>;

export function SaveCreation(arg1:string):Promise<model.Creation>;

export function SaveFragment(arg1:model.Fragment):Promise<number>;
