// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function ClearCollected() {
  return window['go']['main']['App']['ClearCollected']();
}

export function ClearCreations() {
  return window['go']['main']['App']['ClearCreations']();
}

export function GetDataDir() {
  return window['go']['main']['App']['GetDataDir']();
}

export function GetFragmentPool() {
  return window['go']['main']['App']['GetFragmentPool']();
}

export function GetTodayFragments(arg1, arg2) {
  return window['go']['main']['App']['GetTodayFragments'](arg1, arg2);
}

export function LoadCollected(arg1, arg2) {
  return window['go']['main']['App']['LoadCollected'](arg1, arg2);
}

export function LoadCreations(arg1, arg2) {
  return window['go']['main']['App']['LoadCreations'](arg1, arg2);
}

export function ResetGame() {
  return window['go']['main']['App']['ResetGame']();
}

export function SaveCreation(arg1) {
  return window['go']['main']['App']['SaveCreation'](arg1);
}

export function SaveFragment(arg1) {
  return window['go']['main']['App']['SaveFragment'](arg1);
}
