// @ts-check
// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT

export function GenFragment() {
  return window['go']['main']['App']['GenFragment']();
}

export function LoadCollected() {
  return window['go']['main']['App']['LoadCollected']();
}

export function LoadCreations(arg1, arg2) {
  return window['go']['main']['App']['LoadCreations'](arg1, arg2);
}

export function ResetGame() {
  return window['go']['main']['App']['ResetGame']();
}

export function SaveCreation(arg1) {
  return window['go']['main']['App']['SaveCreation'](arg1);
}

export function SaveFragment(arg1) {
  return window['go']['main']['App']['SaveFragment'](arg1);
}
