// Cynhyrchwyd y ffeil hon yn awtomatig. PEIDIWCH Â MODIWL
// This file is automatically generated. DO NOT EDIT
import {main} from '../models';

export function ClearCollected():Promise<void>;

export function ClearCreations():Promise<void>;

export function GetDataDir():Promise<string>;

export function GetFragmentPool():Promise<Array<main.Fragment>>;

export function GetTodayFragments(arg1:number,arg2:number):Promise<main.PaginatedResult>;

export function LoadCollected(arg1:number,arg2:number):Promise<main.PaginatedResult>;

export function LoadCreations(arg1:number,arg2:number):Promise<main.PaginatedResult>;

export function ResetGame():Promise<void>;

export function SaveCreation(arg1:string):Promise<main.Creation>;

export function SaveFragment(arg1:main.Fragment):Promise<void>;
