name: Release

on:
  push:
    tags:
      - '*'

env:
  NODE_OPTIONS: "--max-old-space-size=4096"

jobs:
  build:
    strategy:
      fail-fast: false
      matrix:
        build:
          - name: '文头字脑'
            platform: 'darwin/universal'
            os: 'macos-latest'
          - name: '文头字脑'
            platform: 'linux/amd64'
            os: 'ubuntu-latest'
          - name: '文头字脑'
            platform: 'windows/amd64'
            os: 'windows-latest'
    runs-on: ${{ matrix.build.os }}
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          submodules: recursive

      - name: Set up Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Set up Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'

      - name: Build with Wails
        run: |
          go install github.com/wailsapp/wails/v2/cmd/wails@latest
          wails build -platform ${{ matrix.build.platform }} -name "${{ matrix.build.name }}"
        env:
          CGO_ENABLED: 1

      - name: Upload Artifacts
        uses: actions/upload-artifact@v4
        with:
          name: ${{ matrix.build.name }}-${{ matrix.build.platform }}
          path: build/bin/*
