name: Release Linux App

on:
  release:
    types: [ published ]
  workflow_dispatch:
    inputs:
      tag:
        description: 'Version tag'
        required: true
        default: '1.0.0'

jobs:
  release:
    name: Release Linux App
    runs-on: ubuntu-22.04
    strategy:
      matrix:
        platform:
          - linux/amd64

    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Normalise platform tag
        id: normalise_platform
        shell: bash
        run: |
          tag=$(echo ${{ matrix.platform }} | sed -e 's/\//_/g')
          echo "tag=$tag" >> "$GITHUB_OUTPUT"

      - name: Normalise platform arch
        id: normalise_platform_arch
        run: |
           if [ "${{ matrix.platform }}" == "linux/amd64" ]; then
             echo "arch=x86_64" >> "$GITHUB_OUTPUT"
           elif [ "${{ matrix.platform }}" == "linux/aarch64" ]; then
             echo "arch=aarch64" >> "$GITHUB_OUTPUT"
           fi

      - name: Normalise version tag
        id: normalise_version
        shell: bash
        run: |
          if [ "${{ github.event.release.tag_name }}" == "" ]; then
            version=$(echo ${{ github.event.inputs.tag }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          else
            version=$(echo ${{ github.event.release.tag_name }} | sed -e 's/v//g')
            echo "version=$version" >> "$GITHUB_OUTPUT"
          fi

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Install Ubuntu prerequisites
        run: |
          sudo apt-get update
          sudo apt-get install -y libgtk-3-dev libwebkit2gtk-4.0-dev libfuse-dev libfuse2

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Build frontend assets
        shell: bash
        run: |
          cd frontend
          jq '.version = "${{ steps.normalise_version.outputs.version }}"' package.json > tmp.json
          mv tmp.json package.json
          npm install

      - name: Build wails app for Linux
        shell: bash
        run: |
          CGO_ENABLED=1 wails build -platform ${{ matrix.platform }} \
          -ldflags "-X main.version=${{ steps.normalise_version.outputs.version }}" \
          -o still

      - name: Setup control template
        shell: bash
        run: |
          content=$(cat build/linux/still_0.0.0_amd64/DEBIAN/control)
          name=$(jq -r '.name' wails.json | tr -d ' ' | tr '[:upper:]' '[:lower:]')
          content=$(echo "$content" | sed -e "s/{{.Name}}/$name/g")
          content=$(echo "$content" | sed -e "s/{{.Info.ProductVersion}}/$(jq -r '.info.productVersion' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Author.Name}}/$(jq -r '.author.name' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Author.Email}}/$(jq -r '.author.email' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Info.Comments}}/$(jq -r '.info.comments' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.libwebkit2gtk.PackageName}}/libwebkit2gtk-4.0-37/g")
          echo "$content" > build/linux/still_0.0.0_amd64/DEBIAN/control

      - name: Setup app template
        shell: bash
        run: |
          content=$(cat build/linux/still_0.0.0_amd64/usr/share/applications/still.desktop)
          content=$(echo "$content" | sed -e "s/{{.Info.ProductName}}/$(jq -r '.info.productName' wails.json)/g")
          content=$(echo "$content" | sed -e "s/{{.Info.Comments}}/$(jq -r '.info.comments' wails.json)/g")
          echo "$content" > build/linux/still_0.0.0_amd64/usr/share/applications/still.desktop

      - name: Package up deb file
        shell: bash
        run: |
          mv build/bin/still build/linux/still_0.0.0_amd64/usr/local/bin/
          cd build/linux
          mv still_0.0.0_amd64 "still_${{ steps.normalise_version.outputs.version }}_amd64"
          sed -i 's/0.0.0/${{ steps.normalise_version.outputs.version }}/g' "still_${{ steps.normalise_version.outputs.version }}_amd64/DEBIAN/control"
          dpkg-deb --build -Zxz "still_${{ steps.normalise_version.outputs.version }}_amd64"

      - name: Package up appimage file
        run: |
          curl https://github.com/linuxdeploy/linuxdeploy/releases/download/1-alpha-20240109-1/linuxdeploy-${{ steps.normalise_platform_arch.outputs.arch }}.AppImage \
                -o linuxdeploy \
                -L
          chmod u+x linuxdeploy

          ./linuxdeploy --appdir AppDir

          pushd AppDir
          find /usr/lib* -name WebKitNetworkProcess -exec mkdir -p $(dirname '{}') \; -exec cp --parents '{}' "." \; || true
          find /usr/lib* -name WebKitWebProcess -exec mkdir -p $(dirname '{}') \; -exec cp --parents '{}' "." \; || true
          find /usr/lib* -name libwebkit2gtkinjectedbundle.so -exec mkdir -p $(dirname '{}') \; -exec cp --parents '{}' "." \; || true
          popd

          mkdir -p AppDir/usr/share/icons/hicolor/512x512/apps
          build_dir="build/linux/still_${{ steps.normalise_version.outputs.version }}_amd64"

          cp -r $build_dir/usr/share/icons/hicolor/512x512/apps/still.png AppDir/usr/share/icons/hicolor/512x512/apps/ 2>/dev/null || true
          cp $build_dir/usr/local/bin/still AppDir/usr/bin/

          sed -i 's#/usr/local/bin/still#still#g' $build_dir/usr/share/applications/still.desktop 2>/dev/null || true

          curl -o AppDir/AppRun https://github.com/AppImage/AppImageKit/releases/download/continuous/AppRun-${{ steps.normalise_platform_arch.outputs.arch }} -L

          ./linuxdeploy --appdir AppDir \
             --output=appimage \
             -e $build_dir/usr/local/bin/still \
             -d $build_dir/usr/share/applications/still.desktop

      - name: Rename deb
        working-directory: ./build/linux
        run: mv "still_${{ steps.normalise_version.outputs.version }}_amd64.deb" "still_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.deb"

      - name: Rename appimage
        run: mv still-${{ steps.normalise_platform_arch.outputs.arch }}.AppImage "still_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.AppImage"

      - name: Upload release asset
        uses: softprops/action-gh-release@v1
        with:
          tag_name: v${{ steps.normalise_version.outputs.version }}
          files: |
            ./build/linux/still_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.deb
            still_${{ steps.normalise_version.outputs.version }}_${{ steps.normalise_platform.outputs.tag }}.AppImage
          token: ${{ secrets.GITHUB_TOKEN }}
