name: Release Windows

on:
  release:
    types: [published]

jobs:
  release-windows:
    name: Release Windows App
    runs-on: windows-latest
    steps:
      - name: Checkout source code
        uses: actions/checkout@v4

      - name: Setup Go
        uses: actions/setup-go@v5
        with:
          go-version: '1.26'

      - name: Install wails
        run: go install github.com/wailsapp/wails/v2/cmd/wails@latest

      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '22.x'

      - name: Build wails app for Windows
        run: wails build -platform windows/amd64

      - name: Create zip
        working-directory: ./build/bin
        shell: bash
        run: powershell -Command "Compress-Archive -Path still.exe -DestinationPath still-windows-amd64.zip"

      - name: Upload to Release
        uses: softprops/action-gh-release@v1
        with:
          tag_name: ${{ github.event.release.tag_name }}
          files: build/bin/still-windows-amd64.zip
          token: ${{ secrets.GITHUB_TOKEN }}
